language: node_js
node_js: '8.12.0'

env:
  - NODE_ENV=production PROD_DB_HOSTNAME=$PROD_DB_HOSTNAME PROD_DB_NAME=$PROD_DB_NAME PROD_DB_PASSWORD=$PROD_DB_PASSWORD PROD_DB_PORT=$PROD_DB_PORT PROD_DB_USERNAME=$PROD_DB_USERNAME

cache:
  yarn: true
  directories:
    - node_modules
script:
  - yarn build
deploy:
  skip_cleanup: true
  provider: heroku
  app: test-task-frontend-5
  api_key: $HEROKU_AUTH_TOKEN
  on:
    repo: GTech1256/TestTaskFrontend-5
after_deploy:
  - yarn
  - yarn start
